
# main.py
WIDTH = 900
HEIGHT = 900
GRID_HEIGHT = HEIGHT // 2
GRID_WIDTH = WIDTH // 2

# Snake.py
STARTING_POSITIONS = [(0, 0), (-20, 0), (-40, 0)]

UP = 90
DOWN = 270
LEFT = 180
RIGHT = 0
MOVE_DISTANCE = 23

# scoreboard.py
SCOREBOARD_HEIGHT = GRID_HEIGHT - 35
ALIGNMENT = 'center'
FONT = ('Arial', 24, 'normal')

# food.py
LEFT_RANGE = -GRID_WIDTH + 20
RIGHT_RANGE = GRID_WIDTH - 20
UP_RANGE = SCOREBOARD_HEIGHT - 20
DOWN_RANGE = -GRID_HEIGHT + 20
